### ISSUE TITLE
Expose findBoundaries

### ISSUE THREAD

**Issue by pbvahlst** [eddieantonio/unicode-default-word-boundary#22]
Thank you for great and performant module.

Could you expose findBoundaries() as part of the public API?

We are using the module for af fulltext search engine and it seems that we can gain some extra indexing performance if we could skip the LazySpan object and just slice the string directly.

**Comment by eddieantonio** [comment]
Done! It's in the latest published version:

```javascript
const {findBoundaries} = require("unicode-default-word-boundary")
const array = Array.from(findBoundaries("ᑖᓂᓯ ᑭᔭᐚᐤ!"));
console.log(array)
// prints:
// [ 0, 3, 4, 8, 9 ]
```
