### ISSUE TITLE
Move internal utility functions out of findBoundaries

### ISSUE THREAD

**Issue by pbvahlst** [eddieantonio/unicode-default-word-boundary#28]
Thanks for the latest performance improvements, that did a huge difference.

Doing a little profiling it seems that an extra 8-10% performance can be gained by just moving the:

- `positionAfter()`
- `wordbreakPropertyAt()`
- `isExtendedPictographicAt()`
- `isAHLetter()`
- `isMidNumLetQ()`

... out of the `findBoundaries()` function so the utility functions don't have to be re-instantiated for every call to  `findBoundaries()`. This is of cause only an issue when `findBoundaries()` is called many times.

The first three utility functions would then need to have `text` passed in as an argument.

side note: 
moving rules like WB5 up the stack to just after WB2 also gives a little gain as there in most cases would be more AH-letters than emojis in a text. This is only 3-4% though (for WB5), so if it messes to much with the order and understanding of the code no need to consider it.

**Comment by eddieantonio** [comment]
Thank you! That actually did work!

> moving rules like WB5 up the stack to just after WB2 also gives a little gain as there in most cases would be more AH-letters than emojis in a text. This is only 3-4% though (for WB5), so if it messes to much with the order and understanding of the code no need to consider it.

I decided to pass on this, since it's not a significant enough speed-up and it _technically_ does not follow the default word boundary algorithm.
